version: '3.8'

services:
  cmgi-db:
    image: postgres:14-alpine
    container_name: cmgi-postgres-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cmgi-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    expose:
      - 5432
    networks:
     - cmgi-network

  cmgi-server:
    build: .
    container_name: cmgi-server-container
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@cmgi-db:5432/cmgi-db
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - cmgi-network
    depends_on:
      - cmgi-db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "yarn prisma:push && yarn dev"
    restart: always

networks:
  cmgi-network:
    name: cmgi-network

volumes:
  postgres_data:
